services:
  Postgres:
    build: https://github.com/THD-C/Postgres.git
    image: thd/postgres
    container_name: THD_Postgres
    hostname: Postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - PG-Data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U default -d thdc"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  Mongo:
    build: 
      context: https://github.com/THD-C/Mongo.git
      secrets:
          - github_token
    image: thd/mongo
    container_name: THD_Mongo
    hostname: Mongo
    restart: unless-stopped
    ports:
      - 27017:27017 
    volumes:
      - MO-Data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  Mongo_Manager:
    build: https://github.com/THD-C/Mongo_Manager.git
    image: thd/mongo_manager
    container_name: THD_Mongo_Manager
    hostname: Mongo_Manager
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://Mongo:27017"
    ports:
      - 50052:50051
    depends_on:
      Mongo:
        condition: service_started

  DB_Manager:
    build: https://github.com/THD-C/DB_Manager.git
    image: thd/db_manager
    container_name: THD_DB_Manager
    hostname: DB_Manager
    restart: unless-stopped
    environment:
      POSTGRES_URL: "postgresql://default:PL_tech_hand_elk@Postgres:5432/thdc"
    ports:
      - 50051:50051
    depends_on:
      Postgres:
        condition: service_healthy

  Frontend_API:
    build: https://github.com/THD-C/Frontend_API.git
    image: thd/frontend_api
    container_name: THD_Frontend_API
    hostname: Frontend_API
    restart: unless-stopped
    environment:
      - DB_MANAGER_PORT=50051
      - DB_MANAGER=DB_Manager
      - MONGO_MANAGER_PORT=50051
      - MONGO_MANAGER=Mongo_Manager
    ports:
      - 8000:8000
    depends_on:
      DB_Manager:
        condition: service_started

  Frontend:
    build: https://github.com/THD-C/Frontend.git
    image: thd/frontend
    container_name: THD_Frontend
    hostname: Frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      Frontend_API:
        condition: service_started
    
secrets:
  github_token:
    file: ./.github_token

volumes:
  PG-Data:
  MO-Data: