name: THDc
include:
  - ./Docker/frontend.docker-compose.yaml
  - ./Docker/backend.docker-compose.yaml
  - ./Docker/microservices.docker-compose.yaml
  - ./Docker/database.docker-compose.yaml
  - ./Docker/telemetry.docker-compose.yaml
  - ./Docker/network.docker-compose.yaml
  - ./Docker/volumes.docker-compose.yaml
  - ./Docker/secrets.docker-compose.yaml

services:
  Grafana:
    profiles:
      - Telemetry
    image: grafana/grafana-enterprise:11.1.4
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.15'
          memory: 100M
    container_name: THD_Grafana
    hostname: Grafana
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw
      GF_DATE_FORMATS_DEFAULT_TIMEZONE: Europe/Warsaw
    volumes:
      - ./config/Grafana/datasources:/etc/grafana/provisioning/datasources
      # - ./config/Grafana/dashboards_provisioning:/etc/grafana/provisioning/dashboards
      # - ./config/Grafana/dashboards:/var/lib/grafana/dashboards
      - GrafanaData:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - MicroservicesNet
      - InternetAccessNet
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://Grafana:3000/api/health"]
      start_period: 2s
      interval: 3s
      timeout: 1s
      retries: 5

  App_Proxy:
    profiles:
      - APP
    image: nginxproxy/nginx-proxy:1.6-alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 50M
    container_name: THD_App_Proxy
    hostname: App_Proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - MicroservicesNet
      - InternetAccessNet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - AppProxyLog:/var/log
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://App_Proxy:80/ready"]
      start_period: 2s
      interval: 3s
      timeout: 1s
      retries: 5
    depends_on:
      Frontend:
        condition: service_healthy
      Frontend_API:
        condition: service_healthy
