services:
  Postgres:
    build: https://github.com/THD-C/Postgres.git
    image: thd/postgres
    container_name: THD_Postgres
    hostname: Postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - PG-Data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U default -d thdc"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  DB_Manager:
    build: https://github.com/THD-C/DB_Manager.git
    image: thd/db_manager
    container_name: THD_DB_Manager
    hostname: DB_Manager
    restart: unless-stopped
    ports:
      - 50051:50051
    depends_on:
      Postgres:
        condition: service_healthy

  Frontend_API:
    build: https://github.com/THD-C/Frontend_API.git
    image: thd/frontend_api
    container_name: THD_Frontend_API
    hostname: Frontend_API
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      DB_Manager:
        condition: service_started

  Frontend:
    build: https://github.com/THD-C/Frontend.git
    image: thd/frontend
    container_name: THD_Frontend
    hostname: Frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      Frontend_API:
        condition: service_started
    
volumes:
  PG-Data: