services:
  Frontend_API:
    profiles:
      - APP
    build: https://github.com/THD-C/Frontend_API.git
    image: thd/frontend_api
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 400M
        reservations:
          cpus: '0.25'
          memory: 150M
    container_name: THD_Frontend_API
    hostname: Frontend_API
    restart: unless-stopped
    environment:
      - DB_MANAGER_PORT=50051
      - DB_MANAGER=DB_Manager
      - MONGO_MANAGER_PORT=50051
      - MONGO_MANAGER=Mongo_Manager
      - PRICE_MANAGER_PORT=50051
      - PRICE_MANAGER=CoinGecko_API_internal
      - ORDERS_SERVICE=Order_Service
      - ORDERS_SERVICE_PORT=50051
    # ports:
    #   - 8000:8000
    networks:
      - MicroservicesNet
      - InternetAccessNet
    healthcheck:
      test: curl --fail http://Frontend_API:8000/api/healthcheck
      interval: 30s          
      timeout: 5s            
      retries: 3             
      start_period: 5s  
    depends_on:
      DB_Manager:
        condition: service_healthy
      Mongo_Manager:
        condition: service_healthy