networks:

  ApplicationAccessNet:
    name: Application Access
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"

  InternetAccessNet:
    name: Internet Access
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  
  MicroservicesNet:
    name: Microservices Network
    internal: true
  
  MongoNet:
    name: Mongo Network
    internal: true
  
  PostgresNet:
    name: Postgres Network
    internal: true
  
  RedisNet:
    name: Redis Network
    internal: true