services:
  memcached:
    profiles:
      - Telemetry
    container_name: MemCached_Tempo
    restart: unless-stopped
    image: memcached:1.6.29
    # ports:
    #   - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use

  tempo:
    profiles:
      - Telemetry
    container_name: Tempo
    hostname: Tempo
    restart: unless-stopped
    image: grafana/tempo:main-a46ac6d
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./../config/tempo.yaml:/etc/tempo.yaml
      - TempoData:/var/tempo
    # ports:
    #   - ${TEMPO_JAEGER_PORT}:14268  # jaeger ingest
    #   - ${TEMPO_PORT}:3200   # tempo
    #   - ${TEMPO_GRPC}:9095 # tempo grpc
    #   - ${TEMPO_OTLP_GRCP}:4317  # otlp grpc
    #   - $TEMPO_OTLP_HTTP:4318  # otlp http
    #   - ${TEMPO_OTLP_ZIPKIN}:9411   # zipkin
    depends_on:
      - memcached

  prometheus:
    profiles:
      - Telemetry
    container_name: Prometheus
    hostname: Prometheus
    restart: unless-stopped
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=14d
    volumes:
      - ./../config/prometheus.yaml:/etc/prometheus.yaml
      - PrometheusData:/prometheus
    # ports:
    #   - ${PROMETHEUS_PORT}:9090

  Loki:
    profiles:
      - Telemetry
    image: grafana/loki:2.9.0
    container_name: Loki
    hostname: Loki
    environment:
      TZ: Europe/Warsaw
    restart: unless-stopped
    command:
      -config.file=/etc/loki/loki.yaml
    volumes:
      - ./../config/loki.yaml:/etc/loki/loki.yaml
      - LokiData:/loki
    # ports:
    #   - 3100:3100

  Promtail:
    profiles:
      - Telemetry
    image: grafana/promtail:2.9.0
    container_name: Promtail
    hostname: Promtail
    environment:
      TZ: Europe/Warsaw
    restart: unless-stopped
    command:
      -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./../config/promtail.yaml:/etc/promtail/promtail.yaml
      - AppProxyLog:/var/log/work/
    # ports:
    #   - 9080:9080