apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: reioqwiej32nov
    url: http://Prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m