global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:

rule_files:


scrape_configs:
  - job_name: "Microservices_metrics"
    static_configs:
      - targets: [
          "Mongo_Manager:8111",
          "DB_Manager:8111",
          "Frontend_API:8111",
          "CoinGecko_API:8111",
          "Order_Service:8111"
        ]