server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://Loki:3100/loki/api/v1/push

scrape_configs:

- job_name: Nginx
  pipeline_stages:
    - json:
        expressions:
          timestamp: time_local
          server_name: server_name
          request: request
          status: status
          upstream_status: upstream_status
          traceparent: http_traceparent
          http_referer: http_referer
    - labels:
        request:
        status:
        traceparent:
        http_referer:
    - timestamp:
        source: timestamp
        format: "02/Jan/2006:15:04:05 -0700"
        location: "Europe/Warsaw"
  static_configs:
  - targets:
      - localhost
    labels:
      Service: Nginx
      __path__: /var/log/work/*.log