name: Build ALL Docker Images

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: choice
        default: 'Production'
        options:
          - 'Production'

jobs:
  CheckIfRunning:
    uses: THD-C/The_THDc_App/.github/workflows/.github/workflows/build-service-image.yml@main

  Build:
    needs: CheckIfRunning
    if: ${{ needs.CheckIfRunning.outputs.env_up == 'true' }}
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set github_token secret
        run: |
          echo "${{ secrets.THDCPL_TOKEN }}" > ./.github_token

      - name: Build Images
        run: docker compose --profile APP build --no-cache