name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: choice
        default: 'Production'
        options:
          - 'Production'

jobs:
  CheckIfRunning:
    uses: THD-C/The_THDc_App/.github/workflows/check-self-hosted-runner.yml@main
    secrets: inherit

  Deploy:
    needs: CheckIfRunning
    if: ${{ needs.CheckIfRunning.outputs.isRunnerUp == 'true' }}
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop Existing Containers
        run: docker compose down -v -t 20 --remove-orphans

      - name: Run Containers
        run: docker compose --profile APP up -d --force-recreate