name: Deploy Service
run-name: Deploy ${{ inputs.service }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: choice
        default: 'Production'
        options:
          - 'Production'
      service:
        description: 'Service Repository to build'
        type: choice
        required: true
        options:
          - 'Mongo_Manager'
          - 'DB_Manager'
          - 'Frontend_API'
          - 'Frontend'
          - 'Mongo'
          - 'CoinGecko_API'
          - 'Order_Service'

env:
  COMPOSE_PROFILE_NAME: "APP"

jobs:
  CheckIfRunning:
    uses: THD-C/The_THDc_App/.github/workflows/check-self-hosted-runner.yml@main
    secrets: inherit


  Build:
    needs: CheckIfRunning
    if: ${{ needs.CheckIfRunning.outputs.isRunnerUp == 'true' }}
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set github_token secret
        run: |
          echo "${{ secrets.THDCPL_TOKEN }}" > ./.github_token

      - name: Build Image
        run: docker compose --profile ${{env.COMPOSE_PROFILE_NAME}} build ${{inputs.service}} --no-cache
      
      - name: Stop exitsing container
        run: docker compose --profile ${{env.COMPOSE_PROFILE_NAME}} down ${{inputs.service}} -v
      
      - name: Run Container
        run: docker compose --profile ${{env.COMPOSE_PROFILE_NAME}} up -d

      - name: Clean up deployment server
        run: docker system prune --force --volumes

  RunTests:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Dispatch event
        shell: pwsh
        run: |
          $RepoName = "THD-C/SyntheticTest"
          $WorkflowName = "run-synthetic-tests.yml"

          Invoke-RestMethod -Method Post -Headers @{
            "Accept"               = "application/vnd.github+json"
            "Authorization"        = "Bearer ${{ secrets.THDCPL_TOKEN }}"
            "X-GitHub-Api-Version" = "2022-11-28"
          } -Body (
              @{
                  ref = "main"
              } | ConvertTo-Json
          ) -Uri "https://api.github.com/repos/$RepoName/actions/workflows/$WorkflowName/dispatches"
          
          Write-Host "https://github.com/$RepoName/actions/workflows/$WorkflowName"